# Generated by Django 4.1.5 on 2023-01-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('New_Arrivals', 'New Arrivals'), ('Best_Sellers', 'Best Sellers'), ('m', 'Man'), ('w', 'Women')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
